In [1]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from cvxopt import solvers,matrix

In [37]:
from sklearn.datasets import fetch_openml
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [6]:
f_digits_vec = "digits4000_txt/digits4000_digits_vec.txt"
f_digits_label = "digits4000_txt/digits4000_digits_labels.txt"
f_digits_trainset = "digits4000_txt/digits4000_trainset.txt"
f_digits_testset = "digits4000_txt/digits4000_testset.txt"

In [7]:
digits_vec = np.loadtxt(f_digits_vec)
digits_label = np.loadtxt(f_digits_label)
digits_trainset = np.loadtxt(f_digits_trainset)
digits_testset = np.loadtxt(f_digits_testset)

In [13]:
print(digits_vec.shape)
print(digits_label.shape)
print(digits_trainset.shape)
print(digits_testset.shape)

(4000, 784)
(4000,)
(2000, 2)
(2000, 2)


In [16]:
# test_size: what proportion of original data is used for test set
train_img, test_img, train_lbl, test_lbl = train_test_split(
    digits_vec, digits_label, test_size=1/5.0, random_state=0)

In [18]:
print(train_img.shape)
print(test_img.shape)

(3200, 784)
(800, 784)


In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit on training set only.
scaler.fit(train_img)

# Apply transform to both the training set and the test set.
train_img = scaler.transform(train_img)
test_img = scaler.transform(test_img)

In [20]:
from sklearn.decomposition import PCA

In [21]:
pca = PCA(0.9)

In [22]:
pca.fit(train_img)

PCA(copy=True, iterated_power='auto', n_components=0.9, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [23]:
print(pca.n_components_)

172


In [24]:
train_img = pca.transform(train_img)
test_img = pca.transform(test_img)

In [27]:
print(train_img.shape)

(3200, 172)


In [33]:
from sklearn.svm import SVC
#polynomial
svclassifier_poly = SVC(kernel='poly', degree=8)
svclassifier_poly.fit(train_img, train_lbl)
#Gaussian Kernel
svclassifier_rbf = SVC(kernel='rbf')
svclassifier_rbf.fit(train_img, train_lbl)
#sigmoid Kernel
svclassifier_sigmoid = SVC(kernel='sigmoid')
svclassifier_sigmoid.fit(train_img, train_lbl)


/Users/alfred/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/alfred/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/alfred/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [34]:
test_pred_poly = svclassifier_poly.predict(test_img)
test_pred_rbf = svclassifier_rbf.predict(test_img)
test_pred_sigmoid = svclassifier_sigmoid.predict(test_img)

In [39]:
print(confusion_matrix(test_lbl, test_pred_poly))
print(classification_report(test_lbl, test_pred_poly))

[[59  2  0  0 19  0  0  0  0  1]
 [ 0 77  0  0  3  0  0  0  0  0]
 [ 0  0 48  0 45  0  0  3  0  1]
 [ 0  1  1 37 22  1  0  0  2  0]
 [ 0  0  1  0 83  0  0  1  0  2]
 [ 0  0  0  1 34 43  2  0  1  1]
 [ 0  0  0  0 30  1 54  0  0  0]
 [ 0  0  0  0 11  0  0 47  0  4]
 [ 0  1  1  0 17  1  0  0 61  1]
 [ 0  0  0  0 22  0  0  1  0 57]]
              precision    recall  f1-score   support

         0.0       1.00      0.73      0.84        81
         1.0       0.95      0.96      0.96        80
         2.0       0.94      0.49      0.65        97
         3.0       0.97      0.58      0.73        64
         4.0       0.29      0.95      0.45        87
         5.0       0.93      0.52      0.67        82
         6.0       0.96      0.64      0.77        85
         7.0       0.90      0.76      0.82        62
         8.0       0.95      0.74      0.84        82
         9.0       0.85      0.71      0.78        80

    accuracy                           0.71       800
   macro avg       

In [40]:
print(confusion_matrix(test_lbl, test_pred_rbf))
print(classification_report(test_lbl, test_pred_rbf))

[[77  0  3  0  0  0  1  0  0  0]
 [ 0 77  2  0  0  0  0  0  1  0]
 [ 0  0 96  0  1  0  0  0  0  0]
 [ 0  0  9 50  0  2  0  1  1  1]
 [ 0  0 10  0 75  1  0  0  1  0]
 [ 0  0  7  3  0 70  2  0  0  0]
 [ 0  0 13  0  0  0 72  0  0  0]
 [ 0  0  6  0  0  0  1 54  0  1]
 [ 1  0  8  0  0  2  0  1 70  0]
 [ 0  0  4  2  1  1  0  4  1 67]]
              precision    recall  f1-score   support

         0.0       0.99      0.95      0.97        81
         1.0       1.00      0.96      0.98        80
         2.0       0.61      0.99      0.75        97
         3.0       0.91      0.78      0.84        64
         4.0       0.97      0.86      0.91        87
         5.0       0.92      0.85      0.89        82
         6.0       0.95      0.85      0.89        85
         7.0       0.90      0.87      0.89        62
         8.0       0.95      0.85      0.90        82
         9.0       0.97      0.84      0.90        80

    accuracy                           0.89       800
   macro avg       

In [41]:
print(confusion_matrix(test_lbl, test_pred_sigmoid))
print(classification_report(test_lbl, test_pred_sigmoid))

[[63  0  7  1  1  6  2  0  1  0]
 [ 0 74  3  2  0  0  0  0  1  0]
 [ 8  3 65  4  1  2 11  0  1  2]
 [ 2  1  2 45  0  7  1  0  4  2]
 [ 3  0  2  1 65  0  5  3  1  7]
 [11  2  1  8  2 49  6  0  2  1]
 [ 8  0  6  0  0  5 65  0  1  0]
 [ 1  0  3  0  1  0  0 49  0  8]
 [ 6  6  2  2  2  6  2  0 55  1]
 [ 1  1  1  3  9  3  0  7  2 53]]
              precision    recall  f1-score   support

         0.0       0.61      0.78      0.68        81
         1.0       0.85      0.93      0.89        80
         2.0       0.71      0.67      0.69        97
         3.0       0.68      0.70      0.69        64
         4.0       0.80      0.75      0.77        87
         5.0       0.63      0.60      0.61        82
         6.0       0.71      0.76      0.73        85
         7.0       0.83      0.79      0.81        62
         8.0       0.81      0.67      0.73        82
         9.0       0.72      0.66      0.69        80

    accuracy                           0.73       800
   macro avg       

Refer to the above result, the accuracy of SVM with using Gaussian Kernel is the best.
So we start the do the parameter tunning on the SVM with Gaussian Kernal

In [42]:
from sklearn.model_selection import GridSearchCV 

# defining parameter range 
param_grid = {'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 'kernel': ['rbf']} 

grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3) 

# fitting the model for grid search 
grid.fit(train_img, train_lbl) 

/Users/alfred/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 3 folds for each of 25 candidates, totalling 75 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.106, total=   2.6s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.6s remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.106, total=   2.4s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    4.9s remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.105, total=   2.5s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.106, total=   2.5s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.106, total=   2.5s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.105, total=   2.5s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=0.1, gamma=0.01, kernel=rbf, score=0.310, total=   2.3s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=0.1, gamma=0.01, kernel=rbf, score=0.313, total=   2.5s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=0.1, gamma=0.01, kernel=rbf, score=0.324, total=   2.4s
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV] .

[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.107, total=   2.5s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.106, total=   2.6s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.105, total=   2.8s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=1000, gamma=0.1, kernel=rbf, score=0.179, total=   2.5s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=1000, gamma=0.1, kernel=rbf, score=0.168, total=   2.6s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=1000, gamma=0.1, kernel=rbf, score=0.174, total=   2.5s
[CV] C=1000, gamma=0.01, kernel=rbf ..................................
[CV] ...... C=1000, gamma=0.01, kernel=rbf, score=0.782, total=   2.2s
[CV] C=1000, gamma=0.01, kernel=rbf ..................................
[CV] .

[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed:  2.4min finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [43]:
# print best parameter after tuning 
print(grid.best_params_) 

# print how our model looks after hyper-parameter tuning 
print(grid.best_estimator_) 

{'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}
SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [44]:
#Gaussian Kernel
svclassifier_rbf_tune = SVC(probability=False, kernel='rbf', C=10, gamma=0.001)
svclassifier_rbf_tune.fit(train_img, train_lbl)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [45]:
test_pred_rbf_tune = svclassifier_rbf_tune.predict(test_img)

In [46]:
print(confusion_matrix(test_lbl, test_pred_rbf_tune))
print(classification_report(test_lbl, test_pred_rbf_tune))

[[79  0  0  0  0  1  1  0  0  0]
 [ 0 78  1  0  0  0  0  1  0  0]
 [ 1  0 89  2  1  0  0  4  0  0]
 [ 0  0  2 56  0  3  0  2  1  0]
 [ 0  0  1  0 82  0  0  2  1  1]
 [ 0  0  0  2  3 75  2  0  0  0]
 [ 0  0  3  0  0  1 81  0  0  0]
 [ 0  0  0  0  0  0  1 60  0  1]
 [ 0  0  4  2  0  1  0  0 75  0]
 [ 0  1  1  1  2  2  0  2  0 71]]
              precision    recall  f1-score   support

         0.0       0.99      0.98      0.98        81
         1.0       0.99      0.97      0.98        80
         2.0       0.88      0.92      0.90        97
         3.0       0.89      0.88      0.88        64
         4.0       0.93      0.94      0.94        87
         5.0       0.90      0.91      0.91        82
         6.0       0.95      0.95      0.95        85
         7.0       0.85      0.97      0.90        62
         8.0       0.97      0.91      0.94        82
         9.0       0.97      0.89      0.93        80

    accuracy                           0.93       800
   macro avg       